#!/bin/bash
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

function remove_last_char_if_not_empty() {
  container=("$@")
  if [[ -n "$container" ]]; then
    container=${container::-1}
  fi
  echo "$container"
}

function create_pattern() {
  files_paths_list=("$@")
  pattern=""
  for file_name in $files_paths_list; do
    pattern="${pattern}${file_name}|"
  done
  pattern=$(remove_last_char_if_not_empty "${pattern[*]}")
  echo "$pattern"
}

function filter_array_with_inverted_regEx() {
  files_paths_list=("$@")
  query=$2
  container=""
  if [[ -z "${query}" ]]; then
    container=$files_paths_list
  else
    for value in $files_paths_list; do
      matched_string=$(echo "$value" | grep -v -E "$query")
      if [[ -n "$matched_string" ]]; then
        container="${container}${value} "
      fi
    done
    container=$(remove_last_char_if_not_empty "${container[*]}")
  fi
  echo "$container"
}


ends_with_js_or_jsx=".*\.jsx?$"
ends_with_css=".*\.css$"
ends_with_rb=".*\.rb?$"
ends_with_erb=".*\.html.erb?$"
eslint_exit_code=0
stylelint_exit_code=0
jest_exit_code=0
rubocop_exit_code=0
erb_exit_code=0
not_staged_js_jsx_files=$(git diff --diff-filter=b --name-only | grep -E "$ends_with_js_or_jsx")
not_staged_css_files=$(git diff --diff-filter=b --name-only | grep -E "$ends_with_css")
not_staged_rb_files=$(git diff --diff-filter=b --name-only | grep -E "$ends_with_rb")
not_staged_erb_files=$(git diff --diff-filter=b --name-only | grep -E "$ends_with_erb")
staged_js_jsx_files=$(git diff --cached --diff-filter=d --name-only | grep -E "$ends_with_js_or_jsx")
staged_css_files=$(git diff --cached --diff-filter=d --name-only | grep -E "$ends_with_css")
staged_rb_files=$(git diff --cached --diff-filter=d --name-only | grep -E "$ends_with_rb")
staged_erb_files=$(git diff --cached --diff-filter=d --name-only | grep -E "$ends_with_erb")

if [[ -n "$staged_js_jsx_files" ]]; then
  echo "Running ESLint..."
  ./node_modules/.bin/eslint $staged_js_jsx_files --quiet
  eslint_exit_code=$?
  echo "Running Tests..."
  ./node_modules/.bin/jest
  jest_exit_code=$?
  if [ $jest_exit_code = 0 ]; then
    echo -e "${GREEN} ✔ All tests passed' ${NC}"
  fi
fi
if [[ -n "$staged_css_files" ]]; then
  echo "Running Stylelint..."
  ./node_modules/.bin/stylelint $staged_css_files --stdin --quiet
  stylelint_exit_code=$?
fi
if [[ -n "$staged_rb_files" ]]; then
  echo "Running RuboCop..."  # Add this line for RuboCop
  bundle exec rubocop
  rubocop_exit_code=$?  # Add this line for RuboCop
fi
if [[ -n "$staged_erb_files" ]]; then
  echo "Running Erb lint..."  # Add this line for Erb-lint
  bundle exec erblint --lint-all
  erb_exit_code=$?  # Add this line for Erb-lint
fi
if [ $eslint_exit_code = 0 ] && [ $stylelint_exit_code = 0 ] && [ $jest_exit_code = 0 ] && [ $rubocop_exit_code = 0 ] && [ $erb_exit_code = 0 ]; then
  echo -e "${GREEN} ✔ Committed successfully *^____^* ${NC}"
  exit
else
  echo -e "${RED} ❌ Couldn't commit changes dues to above errors ＞﹏＜ ${NC}"
  exit 1
fi
